export type CREATING_CUSTOMER = 'CUSTOMERS/CREATING_CUSTOMER';
export const CREATING_CUSTOMER: CREATING_CUSTOMER = 'CUSTOMERS/CREATING_CUSTOMER';

export type SET_CUSTOMERS = 'CUSTOMERS/SET_CUSTOMERS';
export const SET_CUSTOMERS: SET_CUSTOMERS = 'CUSTOMERS/SET_CUSTOMERS';

export type ADD_CUSTOMER = 'CUSTOMERS/ADD_CUSTOMER';
export const ADD_CUSTOMER: ADD_CUSTOMER = 'CUSTOMERS/ADD_CUSTOMER';

export type FETCHING_CUSTOMERS = 'CUSTOMERS/FETCHING_CUSTOMERS';
export const FETCHING_CUSTOMERS: FETCHING_CUSTOMERS = 'CUSTOMERS/FETCHING_CUSTOMERS';

export type STOPPED_FETCHING_CUSTOMERS = 'CUSTOMERS/STOPPED_FETCHING_CUSTOMERS';
export const STOPPED_FETCHING_CUSTOMERS: STOPPED_FETCHING_CUSTOMERS = 'CUSTOMERS/STOPPED_FETCHING_CUSTOMERS';
